name: Django Ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest


    steps:
      - uses: actions/checkout@v2

      - name: Set Up Python 3.10.11
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.11

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -m requirements.txt
     - name: Run Migrations
      run: python manage.py 

    - name: Run Tests
      run: python manage.py test